name: GitVersion Semantic Versioning

on:
  workflow_call:  # Allows this workflow to be called from other repositories

jobs:
  gitversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.13.2
        with:
          versionSpec: 6.0.0

      - name: Show last commit
        run: git log -1

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.13.2
        with:
          versionSpec: 6.0.0

      - name: Show GitVersion outputs
        run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"

      - name: Create and push git tag
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          GIT_AUTHOR_NAME="$(git log -1 --pretty=format:'%an')"
          GIT_AUTHOR_EMAIL="$(git log -1 --pretty=format:'%ae')"
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git tag v${{ steps.gitversion.outputs.fullSemVer }}
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin v${{ steps.gitversion.outputs.fullSemVer }}

