name: Python CI/CD

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required by SonarScanner

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests with pytest
      env:
        PYTHONPATH: '.' # Add the project root to the Python path
      run: |
        pytest tests/ --cov=my_app_project/ --cov-report=xml --junitxml=junit.xml


    # - name: SonarCloud Scan
    #   uses: SonarSource/sonarcloud-github-action@v2.1.2
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     # Pass test coverage report to SonarCloud
    #     args: >
    #       -Dsonar.python.xunit.reportPaths=junit.xml
    #       -Dsonar.python.coverage.reportPaths=coverage.xml

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ${{ secrets.AWS_REGION }}

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      env:
        # ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        # ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: ${{ inputs.tag }}
      run: |
        echo "Building Docker image with tag: $IMAGE_TAG"
        # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
