name: Centralized Tagging

on:
  workflow_call:
    outputs:
      needs_tag:
        description: "Whether a tag is needed"
        value: ${{ jobs.check-tag.outputs.needs_tag }}
  push:
    branches:
      - main
      - QA
      - dev
      - feature/**


jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      needs_tag: ${{ steps.check_tag.outputs.needs_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if 1.0.0 tag exists
        id: check_tag
        run: |
          if ! git tag | grep -q "^v1.0.0$"; then
              git tag v1.0.0
              git push origin v1.0.0
              echo "needs_tag=true" >> $GITHUB_OUTPUT
          else
              echo "needs_tag=false" >> $GITHUB_OUTPUT
          fi
      - name: Debug needs_tag
        run: echo "needs_tag=${{ steps.check_tag.outputs.needs_tag }}"

